In [10]:
import numpy as np

In [11]:
filename = "presidential_polls.csv"
use_cols_name = ["adjpoll_clinton", "adjpoll_trump", "adjpoll_johnson"]

In [12]:
# 将文件的第一行内容处理为列表
all_cols_name = open(filename, "r").readline()[:-1].split(",")
print(all_cols_name)

['cycle', 'branch', 'type', 'matchup', 'forecastdate', 'state', 'startdate', 'enddate', 'pollster', 'grade', 'samplesize', 'population', 'poll_wt', 'rawpoll_clinton', 'rawpoll_trump', 'rawpoll_johnson', 'rawpoll_mcmullin', 'adjpoll_clinton', 'adjpoll_trump', 'adjpoll_johnson', 'adjpoll_mcmullin', 'multiversions', 'url', 'poll_id', 'question_id', 'createddate', 'timestamp']


In [13]:
# 1. 获取指定列的索引列表
use_cols_index = [all_cols_name.index(col) for col in use_cols_name]
print(use_cols_index)

[17, 18, 19]


In [17]:
# 2. 读取文件指定的列数据，并将数字部分索引出来
arr = np.genfromtxt(filename, delimiter=",", dtype=str, usecols=use_cols_index)
data_arr = arr[1:]
print(data_arr)

[['42.6414' '40.86509' '5.675099']
 ['43.29659' '44.72984' '3.401513']
 ['46.29779' '40.72604' '6.401513']
 ..., 
 ['45.9713' '39.97518' '']
 ['45.2939' '46.66175' '1.596946']
 ['31.62721' '44.65947' '']]


In [20]:
# 3. 数据清洗：将空字符串替换为"0"，再将数据雷系修改为浮点型
clean_data_arr = np.where(data_arr == "", "0", data_arr).astype(float)
print(clean_data_arr)

[[ 42.6414    40.86509    5.675099]
 [ 43.29659   44.72984    3.401513]
 [ 46.29779   40.72604    6.401513]
 ..., 
 [ 45.9713    39.97518    0.      ]
 [ 45.2939    46.66175    1.596946]
 [ 31.62721   44.65947    0.      ]]


In [31]:
# 4. 统计数据结果：
print("票选统计结果：")
print("{} : 结果为 {:.2f}".format(use_cols_name[0], np.sum(clean_data_arr[:, 0])))
print("{} : 结果为 {:.2f}".format(use_cols_name[1], np.sum(clean_data_arr[:, 1])))
print("{} : 结果为 {:.2f}".format(use_cols_name[2], np.sum(clean_data_arr[:, 2])))

票选统计结果：
adjpoll_clinton : 结果为 440402.88
adjpoll_trump : 结果为 430409.65
adjpoll_johnson : 结果为 31131.26


In [ ]:
# 选民票-》总统候选人，最后决定两个总统候选人参与选举人投票
# 选举人票-》 美国总统，538张选举人票，最先获取270张就是美国总统。