In [2]:
import numpy as np

In [2]:
import random
import time
import numpy as np
a = []
for i in range(100000000): 
    a.append(random.random())
t1 = time.time()
sum1=sum(a)
t2=time.time()

b=np.array(a)
t4=time.time()
sum3=np.sum(b)
t5=time.time()
print(t2-t1, t5-t4)

1.6206438541412354 0.20034408569335938


In [3]:
# 创建数组
a1 = np.array([1,2,3,4])

In [4]:
type(a1)

numpy.ndarray

In [14]:
a2 = np.array([[1,2,3],[4,5,6]], dtype=np.int32)

In [15]:
a2.dtype

dtype('int32')

In [8]:
a2.shape

(2, 3)

In [9]:
a3 = np.array([[[1,2,3],[4,5,6]], [[1,20,3],[4,5,6]]])

In [10]:
a3.shape

(2, 2, 3)

In [16]:
a2.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [17]:
np.ones([2, 3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [18]:
np.zeros([2, 3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [19]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]])

In [20]:
arr2 = np.array(arr1)

In [21]:
arr3 = np.asarray(arr1)

In [22]:
arr2,arr3

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[1, 2, 3, 4],
        [5, 6, 7, 8]]))

In [23]:
arr1[0] = 1

In [24]:
arr1

array([[1, 1, 1, 1],
       [5, 6, 7, 8]])

In [25]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
arr3

array([[1, 1, 1, 1],
       [5, 6, 7, 8]])

In [28]:
np.linspace(1, 100, 5)

array([   1.  ,   25.75,   50.5 ,   75.25,  100.  ])

In [29]:
np.random.rand(10)

array([ 0.54097986,  0.62676743,  0.75851632,  0.37584266,  0.54038718,
        0.97896939,  0.45557418,  0.71477343,  0.24423639,  0.87661583])

In [30]:
np.random.uniform(0, 100)

57.37919556836807

In [32]:
np.random.randint(100)

50

In [33]:
np.random.normal(1.75, 0.01, (3,4))

array([[ 1.76899819,  1.75227671,  1.76595346,  1.73671895],
       [ 1.7645325 ,  1.74781703,  1.76880733,  1.77378404],
       [ 1.78177375,  1.76242628,  1.74544991,  1.76412167]])

In [69]:
# 生成500个公司，504天的股票涨跌幅数据
stock_day_rise = np.random.normal(0, 1, (500, 504))

In [70]:
stock_day_rise[0, :100]

array([ 0.33675073,  0.49791785, -1.42625534,  1.72146349,  1.49564772,
       -0.14395441, -0.53486077, -1.01683797, -0.26320741,  1.46946843,
        0.49903835, -0.63412547, -1.36554951, -1.35537644, -0.91481991,
       -0.09388883,  0.98279795,  0.17740103,  0.44633569,  0.95698892,
        0.88184631,  0.5045085 , -0.96724467,  2.0791283 ,  1.43566484,
       -0.27077951,  1.55810737, -0.8620433 , -0.7222599 , -0.23921774,
       -0.99919498, -0.09751174, -0.33534076, -0.17717832, -0.19124501,
       -0.54536609,  0.24991086,  1.87252792,  0.8569767 , -0.46727234,
       -0.63388162,  0.00466305, -0.5742778 , -0.1238818 , -1.07203293,
       -0.22308679, -0.40687096,  2.02552945, -1.09542092,  0.82655946,
       -0.19354991,  0.80598152, -0.32356187,  0.31664829, -0.4866073 ,
        0.34586269, -0.2434032 ,  0.02723507,  0.28730469,  0.2871953 ,
       -1.24309232, -1.47717662, -0.4354775 , -0.68503694,  0.55805467,
       -1.13119244,  0.23337761,  0.48688017,  1.71867471,  0.60

In [61]:
# 获取签4个公司，前4天的交易日涨跌幅情况
np.round(stock_day_rise[0:3, 0:4], 4)

array([[-0.2658,  1.7478,  1.6037, -1.333 ],
       [ 0.8105,  0.9198, -0.32  ,  1.4928],
       [ 0.8928,  0.7163, -0.2653,  2.15  ]])

In [46]:
a = np.array([[[1,2,3], [4,5,6]], [[5,4,3],[1,2,3]]])

In [47]:
a.shape

(2, 2, 3)

(2, 3)

In [52]:
stock_day_rise.shape

(500, 504)

In [64]:
stock_day_rise.reshape([504, 500]).astype(int)

stock_day_rise[:2, :5]

array([[-0.26581563,  1.74783369,  1.60368852, -1.33301525,  0.36286917],
       [ 0.81051601,  0.91977314, -0.31998908,  1.49283034, -2.31734299]])

In [63]:
# 获取前两个股票， 涨幅大于0.5的数据拿出来
stock_day_rise[:2, :5] > 0.5

array([[False,  True,  True, False, False],
       [ True,  True, False,  True, False]], dtype=bool)

In [83]:
# 涨幅大于0.5的标记为1
tmp = stock_day_rise[:2, :5].copy()

# tmp[stock_day_rise[:2, :5] > 0.5] = 1

In [75]:
tmp

array([[ 0.33675073,  0.49791785, -1.42625534,  1.72146349,  1.49564772],
       [-0.43742886, -0.42929861, -0.13558434,  1.37309381,  1.1492558 ]])

In [73]:
stock_day_rise

array([[ 0.33675073,  0.49791785, -1.42625534, ...,  0.65381901,
         0.92226226,  1.97454653],
       [-0.43742886, -0.42929861, -0.13558434, ...,  0.93480778,
        -0.74346096,  0.16359958],
       [-0.46777922, -0.22858915,  0.2208206 , ..., -0.36461786,
         0.24108975, -0.49465474],
       ..., 
       [ 1.04127413,  1.13312112,  0.68538774, ...,  0.0303607 ,
        -0.62219197,  0.29211796],
       [ 0.06378053, -0.08087569, -0.68914384, ..., -1.50296259,
         0.64908626,  0.45566639],
       [ 0.88713104, -1.63377401,  0.38408291, ..., -0.00512355,
        -0.19020956, -0.54402266]])

In [76]:
# 判断这两个公司的所有涨幅是否大于0
np.all(tmp > 0)

False

In [77]:
narr = np.array([[1,2,3,1,1], [2,3,4,3,2]])

In [78]:
np.unique(narr)

array([1, 2, 3, 4])

In [79]:
# np.where 涨幅大于0.5的标记为1,否则为0
np.where(tmp > 0.5, 1, 0)

array([[0, 0, 0, 1, 1],
       [0, 0, 0, 1, 1]])

In [84]:
np.where(np.logical_and(tmp > 0.5, tmp < 1), 1, 0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [91]:
# 分析前四个股票，前4天的涨跌幅最大值，最小值等等
temp = stock_day_rise[:4, :4].copy()
temp

array([[ 0.33675073,  0.49791785, -1.42625534,  1.72146349],
       [-0.43742886, -0.42929861, -0.13558434,  1.37309381],
       [-0.46777922, -0.22858915,  0.2208206 , -0.05264679],
       [-0.21744261, -0.54448154, -0.90977201,  1.41247757]])

In [92]:
# axis指定的是轴，axis=0按列求最大值 , axis=1按行求最大值
print("前四个股票的最大涨幅{}".format(np.max(temp, axis=1)))

前四个股票的最大涨幅[ 1.72146349  1.37309381  0.2208206   1.41247757]


In [90]:
# 获取最小涨幅，平均值，方差 ，针对股票来说
print("最大跌幅{}".format(np.min(temp, axis=1)))
print("振幅幅度{}".format(np.std(temp, axis=1)))
print("平均涨跌幅{}".format(np.mean(temp, axis=1)))

最大跌幅[-1.42625534 -0.43742886 -0.46777922 -0.90977201]
振幅幅度[ 1.12247591  0.74917308  0.25142416  0.88737265]
平均涨跌幅[ 0.28246918  0.0926955  -0.13204864 -0.06480465]


In [93]:
# 统计出哪一只股票在某个交易日的涨幅最大, axis=1,返回某一行最大值的下标
print("最大涨幅的天数{}".format(np.argmax(temp, axis=1)))

最大涨幅的天数[3 3 2 3]


In [107]:
# 数组的运算， 数组与数
# 底层运算，避免一些for循环操作
a = np.array([[1,2,3], [4,5,6]])

In [108]:
a + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [109]:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [110]:
b = [1,2,3]

In [111]:
b * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [112]:
c = np.array([[5,6,7], [9,10,11]])

In [113]:
a + c

array([[ 6,  8, 10],
       [13, 15, 17]])

In [114]:
a * c

array([[ 5, 12, 21],
       [36, 50, 66]])

In [115]:
# 矩阵的相乘
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[2], [2], [2]])

In [117]:
# 使用matmul的函数
np.matmul(a, b)

array([[12],
       [30]])

In [118]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[7,8,9], [10,11,12]])

In [119]:
# numpy读取数据
data = np.genfromtxt("./data/numpy_test/test.csv", delimiter=',')

In [120]:
data

array([[   nan,    nan,    nan,    nan],
       [   1. ,  123. ,    1.4,   23. ],
       [   2. ,  110. ,    nan,   18. ],
       [   3. ,    nan,    2.1,   19. ]])

In [121]:
type(np.nan)

float

In [ ]:
# numpy当中nan是一个float类型

# 处理nan